name: cfw_flutter
description: "Clean-room port of Clash for Windows UI on Flutter (Windows desktop)."
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # 窗口与托盘管理
  window_manager: ^0.3.9
  tray_manager: ^0.2.2
  windows_single_instance: ^1.1.0
  
  # 网络请求 (解决 Dio 报错)
  dio: ^5.4.1
  web_socket_channel: ^2.4.0
  url_launcher: ^6.2.5
  
  # 文件选择 (解决 FilePicker 报错)
  file_picker: ^8.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
  # 注册本地 Emoji 字体
  fonts:
    - family: TwemojiMozilla
      fonts:
        - asset: assets/fonts/TwemojiMozilla.ttf